server:
  port: 8082

spring:
  datasource:
    username: root
    password: c147852.
    #url中database为对应的数据库名称
    url: jdbc:mysql://110.40.195.72:3306/practiceDB?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#showSql
logging:
  level:
    com.example.demo.mapper: debug
